# Generated by Django 4.2 on 2023-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='UpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
